const statedata = [
  {
    State_Name: "Andaman and Nicobar Islands",
    District_Name: "NICOBARS",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Arecanut",
    Area: 1254.0,
    Production: 2000.0,
  },
  {
    State_Name: "Andaman and Nicobar Islands",
    District_Name: "NICOBARS",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Other Kharif pulses",
    Area: 2.0,
    Production: 1.0,
  },
  {
    State_Name: "Andaman and Nicobar Islands",
    District_Name: "NICOBARS",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Rice",
    Area: 102.0,
    Production: 321.0,
  },
  {
    State_Name: "Andaman and Nicobar Islands",
    District_Name: "NICOBARS",
    Crop_Year: 2000,
    Season: "Whole Year",
    Crop: "Banana",
    Area: 176.0,
    Production: 641.0,
  },
  {
    State_Name: "Andaman and Nicobar Islands",
    District_Name: "NICOBARS",
    Crop_Year: 2000,
    Season: "Whole Year",
    Crop: "Cashewnut",
    Area: 720.0,
    Production: 165.0,
  },
  {
    State_Name: "Andaman and Nicobar Islands",
    District_Name: "NICOBARS",
    Crop_Year: 2000,
    Season: "Whole Year",
    Crop: "Coconut",
    Area: 18168.0,
    Production: 65100000.0,
  },
  {
    State_Name: "Andaman and Nicobar Islands",
    District_Name: "NICOBARS",
    Crop_Year: 2000,
    Season: "Whole Year",
    Crop: "Dry ginger",
    Area: 36.0,
    Production: 100.0,
  },
  {
    State_Name: "Andaman and Nicobar Islands",
    District_Name: "NICOBARS",
    Crop_Year: 2000,
    Season: "Whole Year",
    Crop: "Sugarcane",
    Area: 1.0,
    Production: 2.0,
  },
  {
    State_Name: "Andaman and Nicobar Islands",
    District_Name: "NICOBARS",
    Crop_Year: 2000,
    Season: "Whole Year",
    Crop: "Sweet potato",
    Area: 5.0,
    Production: 15.0,
  },
  {
    State_Name: "Andaman and Nicobar Islands",
    District_Name: "NICOBARS",
    Crop_Year: 2000,
    Season: "Whole Year",
    Crop: "Tapioca",
    Area: 40.0,
    Production: 169.0,
  },
  {
    State_Name: "Andaman and Nicobar Islands",
    District_Name: "NICOBARS",
    Crop_Year: 2001,
    Season: "Kharif",
    Crop: "Arecanut",
    Area: 1254.0,
    Production: 2061.0,
  },
  {
    State_Name: "Andaman and Nicobar Islands",
    District_Name: "NICOBARS",
    Crop_Year: 2001,
    Season: "Kharif",
    Crop: "Other Kharif pulses",
    Area: 2.0,
    Production: 1.0,
  },
  {
    State_Name: "Andaman and Nicobar Islands",
    District_Name: "NICOBARS",
    Crop_Year: 2001,
    Season: "Kharif",
    Crop: "Rice",
    Area: 83.0,
    Production: 300.0,
  },
  {
    State_Name: "Andaman and Nicobar Islands",
    District_Name: "NICOBARS",
    Crop_Year: 2001,
    Season: "Whole Year",
    Crop: "Cashewnut",
    Area: 719.0,
    Production: 192.0,
  },
  {
    State_Name: "Andaman and Nicobar Islands",
    District_Name: "NICOBARS",
    Crop_Year: 2001,
    Season: "Whole Year",
    Crop: "Coconut",
    Area: 18190.0,
    Production: 64430000.0,
  },
  {
    State_Name: "Andhra Pradesh",
    District_Name: "ANANTAPUR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Arhar\\/Tur",
    Area: 21400.0,
    Production: 2600.0,
  },
  {
    State_Name: "Andhra Pradesh",
    District_Name: "ANANTAPUR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Bajra",
    Area: 1400.0,
    Production: 500.0,
  },
  {
    State_Name: "Andhra Pradesh",
    District_Name: "ANANTAPUR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Castor seed",
    Area: 1000.0,
    Production: 100.0,
  },
  {
    State_Name: "Andhra Pradesh",
    District_Name: "ANANTAPUR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Cotton(lint)",
    Area: 7300.0,
    Production: 9400.0,
  },
  {
    State_Name: "Andhra Pradesh",
    District_Name: "ANANTAPUR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Dry chillies",
    Area: 3700.0,
    Production: 7100.0,
  },
  {
    State_Name: "Andhra Pradesh",
    District_Name: "ANANTAPUR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Groundnut",
    Area: 650800.0,
    Production: 228400.0,
  },
  {
    State_Name: "Andhra Pradesh",
    District_Name: "ANANTAPUR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Horse-gram",
    Area: 3300.0,
    Production: 1000.0,
  },
  {
    State_Name: "Andhra Pradesh",
    District_Name: "ANANTAPUR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Jowar",
    Area: 10100.0,
    Production: 10200.0,
  },
  {
    State_Name: "Andhra Pradesh",
    District_Name: "ANANTAPUR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Korra",
    Area: 2200.0,
    Production: 700.0,
  },
  {
    State_Name: "Andhra Pradesh",
    District_Name: "ANANTAPUR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Maize",
    Area: 2800.0,
    Production: 4900.0,
  },
  {
    State_Name: "Andhra Pradesh",
    District_Name: "ANANTAPUR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Moong(Green Gram)",
    Area: 1300.0,
    Production: 500.0,
  },
  {
    State_Name: "Andhra Pradesh",
    District_Name: "ANANTAPUR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Other Kharif pulses",
    Area: 800.0,
    Production: 100.0,
  },
  {
    State_Name: "Andhra Pradesh",
    District_Name: "ANANTAPUR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Ragi",
    Area: 6700.0,
    Production: 11800.0,
  },
  {
    State_Name: "Andhra Pradesh",
    District_Name: "ANANTAPUR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Rice",
    Area: 35600.0,
    Production: 75400.0,
  },
  {
    State_Name: "Andhra Pradesh",
    District_Name: "ANANTAPUR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Sugarcane",
    Area: 700.0,
    Production: 72900.0,
  },
  {
    State_Name: "Arunachal Pradesh",
    District_Name: "ANJAW",
    Crop_Year: 2004,
    Season: "Kharif",
    Crop: "Maize",
    Area: 2453.0,
    Production: 2674.0,
  },
  {
    State_Name: "Arunachal Pradesh",
    District_Name: "ANJAW",
    Crop_Year: 2004,
    Season: "Kharif",
    Crop: "Rice",
    Area: 3342.0,
    Production: 1914.0,
  },
  {
    State_Name: "Arunachal Pradesh",
    District_Name: "ANJAW",
    Crop_Year: 2004,
    Season: "Kharif",
    Crop: "Small millets",
    Area: 532.0,
    Production: 495.0,
  },
  {
    State_Name: "Arunachal Pradesh",
    District_Name: "ANJAW",
    Crop_Year: 2004,
    Season: "Rabi",
    Crop: "Wheat",
    Area: 30.0,
    Production: 60.0,
  },
  {
    State_Name: "Arunachal Pradesh",
    District_Name: "ANJAW",
    Crop_Year: 2004,
    Season: "Whole Year",
    Crop: "Dry chillies",
    Area: 13.0,
    Production: 18.0,
  },
  {
    State_Name: "Arunachal Pradesh",
    District_Name: "ANJAW",
    Crop_Year: 2004,
    Season: "Whole Year",
    Crop: "Dry ginger",
    Area: 60.0,
    Production: 420.0,
  },
  {
    State_Name: "Arunachal Pradesh",
    District_Name: "ANJAW",
    Crop_Year: 2004,
    Season: "Whole Year",
    Crop: "Potato",
    Area: 86.0,
    Production: 688.0,
  },
  {
    State_Name: "Arunachal Pradesh",
    District_Name: "ANJAW",
    Crop_Year: 2004,
    Season: "Whole Year",
    Crop: "Sugarcane",
    Area: 5.0,
    Production: 50.0,
  },
  {
    State_Name: "Arunachal Pradesh",
    District_Name: "ANJAW",
    Crop_Year: 2004,
    Season: "Whole Year",
    Crop: "Turmeric",
    Area: 8.0,
    Production: 20.0,
  },
  {
    State_Name: "Arunachal Pradesh",
    District_Name: "ANJAW",
    Crop_Year: 2005,
    Season: "Kharif",
    Crop: "Maize",
    Area: 3000.0,
    Production: 2700.0,
  },
  {
    State_Name: "Arunachal Pradesh",
    District_Name: "ANJAW",
    Crop_Year: 2005,
    Season: "Kharif",
    Crop: "Rice",
    Area: 3400.0,
    Production: 5000.0,
  },
  {
    State_Name: "Arunachal Pradesh",
    District_Name: "ANJAW",
    Crop_Year: 2005,
    Season: "Kharif",
    Crop: "Small millets",
    Area: 585.0,
    Production: 525.0,
  },
  {
    State_Name: "Arunachal Pradesh",
    District_Name: "ANJAW",
    Crop_Year: 2005,
    Season: "Rabi",
    Crop: "Wheat",
    Area: 32.0,
    Production: 65.0,
  },
  {
    State_Name: "Arunachal Pradesh",
    District_Name: "ANJAW",
    Crop_Year: 2005,
    Season: "Whole Year",
    Crop: "Dry chillies",
    Area: 20.0,
    Production: 28.0,
  },
  {
    State_Name: "Arunachal Pradesh",
    District_Name: "ANJAW",
    Crop_Year: 2005,
    Season: "Whole Year",
    Crop: "Dry ginger",
    Area: 65.0,
    Production: 455.0,
  },
  {
    State_Name: "Assam",
    District_Name: "BAKSA",
    Crop_Year: 2005,
    Season: "Autumn",
    Crop: "Rice",
    Area: 17083.0,
    Production: 15415.0,
  },
  {
    State_Name: "Assam",
    District_Name: "BAKSA",
    Crop_Year: 2005,
    Season: "Kharif",
    Crop: "Arhar\\/Tur",
    Area: 191.0,
    Production: 115.0,
  },
  {
    State_Name: "Assam",
    District_Name: "BAKSA",
    Crop_Year: 2005,
    Season: "Kharif",
    Crop: "Castor seed",
    Area: 22.0,
    Production: 11.0,
  },
  {
    State_Name: "Assam",
    District_Name: "BAKSA",
    Crop_Year: 2005,
    Season: "Kharif",
    Crop: "Cotton(lint)",
    Area: 8.0,
    Production: 4.0,
  },
  {
    State_Name: "Assam",
    District_Name: "BAKSA",
    Crop_Year: 2005,
    Season: "Kharif",
    Crop: "Jute",
    Area: 382.0,
    Production: 3540.0,
  },
  {
    State_Name: "Assam",
    District_Name: "BAKSA",
    Crop_Year: 2005,
    Season: "Kharif",
    Crop: "Maize",
    Area: 179.0,
    Production: 134.0,
  },
  {
    State_Name: "Assam",
    District_Name: "BAKSA",
    Crop_Year: 2005,
    Season: "Kharif",
    Crop: "Mesta",
    Area: 98.0,
    Production: 381.0,
  },
  {
    State_Name: "Assam",
    District_Name: "BAKSA",
    Crop_Year: 2005,
    Season: "Kharif",
    Crop: "Niger seed",
    Area: 518.0,
    Production: 269.0,
  },
  {
    State_Name: "Assam",
    District_Name: "BAKSA",
    Crop_Year: 2005,
    Season: "Kharif",
    Crop: "Sesamum",
    Area: 509.0,
    Production: 266.0,
  },
  {
    State_Name: "Assam",
    District_Name: "BAKSA",
    Crop_Year: 2005,
    Season: "Kharif",
    Crop: "Small millets",
    Area: 247.0,
    Production: 110.0,
  },
  {
    State_Name: "Assam",
    District_Name: "BAKSA",
    Crop_Year: 2005,
    Season: "Rabi",
    Crop: "Gram",
    Area: 58.0,
    Production: 26.0,
  },
  {
    State_Name: "Assam",
    District_Name: "BAKSA",
    Crop_Year: 2005,
    Season: "Rabi",
    Crop: "Linseed",
    Area: 728.0,
    Production: 422.0,
  },
  {
    State_Name: "Assam",
    District_Name: "BAKSA",
    Crop_Year: 2005,
    Season: "Rabi",
    Crop: "Masoor",
    Area: 1973.0,
    Production: 1026.0,
  },
  {
    State_Name: "Assam",
    District_Name: "BAKSA",
    Crop_Year: 2005,
    Season: "Rabi",
    Crop: "Moong(Green Gram)",
    Area: 295.0,
    Production: 126.0,
  },
  {
    State_Name: "Assam",
    District_Name: "BAKSA",
    Crop_Year: 2005,
    Season: "Rabi",
    Crop: "Other  Rabi pulses",
    Area: 5239.0,
    Production: 3217.0,
  },
  {
    State_Name: "Bihar",
    District_Name: "ARARIA",
    Crop_Year: 1997,
    Season: "Autumn",
    Crop: "Rice",
    Area: 17876.0,
    Production: 21397.0,
  },
  {
    State_Name: "Bihar",
    District_Name: "ARARIA",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Arhar\\/Tur",
    Area: 354.0,
    Production: 426.0,
  },
  {
    State_Name: "Bihar",
    District_Name: "ARARIA",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Dry ginger",
    Area: 78.0,
    Production: 110.0,
  },
  {
    State_Name: "Bihar",
    District_Name: "ARARIA",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Groundnut",
    Area: 8.0,
    Production: 10.0,
  },
  {
    State_Name: "Bihar",
    District_Name: "ARARIA",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Jute",
    Area: 39159.0,
    Production: 493403.0,
  },
  {
    State_Name: "Bihar",
    District_Name: "ARARIA",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Maize",
    Area: 3919.0,
    Production: 8691.0,
  },
  {
    State_Name: "Bihar",
    District_Name: "ARARIA",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Mesta",
    Area: 2852.0,
    Production: 19346.0,
  },
  {
    State_Name: "Bihar",
    District_Name: "ARARIA",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Other Kharif pulses",
    Area: 342.0,
    Production: 172.0,
  },
  {
    State_Name: "Bihar",
    District_Name: "ARARIA",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Sesamum",
    Area: 4.0,
    Production: 2.0,
  },
  {
    State_Name: "Bihar",
    District_Name: "ARARIA",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Barley",
    Area: 84.0,
    Production: 87.0,
  },
  {
    State_Name: "Bihar",
    District_Name: "ARARIA",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Gram",
    Area: 1145.0,
    Production: 444.0,
  },
  {
    State_Name: "Bihar",
    District_Name: "ARARIA",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Linseed",
    Area: 1946.0,
    Production: 1092.0,
  },
  {
    State_Name: "Bihar",
    District_Name: "ARARIA",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Maize",
    Area: 3250.0,
    Production: 7543.0,
  },
  {
    State_Name: "Bihar",
    District_Name: "ARARIA",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Other  Rabi pulses",
    Area: 126.0,
    Production: 66.0,
  },
  {
    State_Name: "Bihar",
    District_Name: "ARARIA",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Rapeseed &Mustard",
    Area: 3060.0,
    Production: 2084.0,
  },
  {
    State_Name: "Chandigarh",
    District_Name: "CHANDIGARH",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Arhar\\/Tur",
    Area: 8.0,
    Production: 8.0,
  },
  {
    State_Name: "Chandigarh",
    District_Name: "CHANDIGARH",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Maize",
    Area: 380.0,
    Production: 1330.0,
  },
  {
    State_Name: "Chandigarh",
    District_Name: "CHANDIGARH",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Moong(Green Gram)",
    Area: 3.0,
    Production: 3.0,
  },
  {
    State_Name: "Chandigarh",
    District_Name: "CHANDIGARH",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Rice",
    Area: 120.0,
    Production: 360.0,
  },
  {
    State_Name: "Chandigarh",
    District_Name: "CHANDIGARH",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Urad",
    Area: 12.0,
    Production: 10.0,
  },
  {
    State_Name: "Chandigarh",
    District_Name: "CHANDIGARH",
    Crop_Year: 1998,
    Season: "Rabi",
    Crop: "Gram",
    Area: 4.0,
    Production: 4.0,
  },
  {
    State_Name: "Chandigarh",
    District_Name: "CHANDIGARH",
    Crop_Year: 1998,
    Season: "Rabi",
    Crop: "Masoor",
    Area: 2.0,
    Production: 3.0,
  },
  {
    State_Name: "Chandigarh",
    District_Name: "CHANDIGARH",
    Crop_Year: 1998,
    Season: "Rabi",
    Crop: "Rapeseed &Mustard",
    Area: 120.0,
    Production: 130.0,
  },
  {
    State_Name: "Chandigarh",
    District_Name: "CHANDIGARH",
    Crop_Year: 1998,
    Season: "Rabi",
    Crop: "Wheat",
    Area: 880.0,
    Production: 3960.0,
  },
  {
    State_Name: "Chandigarh",
    District_Name: "CHANDIGARH",
    Crop_Year: 1998,
    Season: "Whole Year",
    Crop: "Onion",
    Area: 18.0,
    Production: 450.0,
  },
  {
    State_Name: "Chandigarh",
    District_Name: "CHANDIGARH",
    Crop_Year: 1998,
    Season: "Whole Year",
    Crop: "Potato",
    Area: 130.0,
    Production: 3250.0,
  },
  {
    State_Name: "Chandigarh",
    District_Name: "CHANDIGARH",
    Crop_Year: 1999,
    Season: "Kharif",
    Crop: "Arhar\\/Tur",
    Area: 80.0,
    Production: 80.0,
  },
  {
    State_Name: "Chandigarh",
    District_Name: "CHANDIGARH",
    Crop_Year: 1999,
    Season: "Kharif",
    Crop: "Maize",
    Area: 325.0,
    Production: 810.0,
  },
  {
    State_Name: "Chandigarh",
    District_Name: "CHANDIGARH",
    Crop_Year: 1999,
    Season: "Kharif",
    Crop: "Moong(Green Gram)",
    Area: 2.0,
    Production: 2.0,
  },
  {
    State_Name: "Chandigarh",
    District_Name: "CHANDIGARH",
    Crop_Year: 1999,
    Season: "Kharif",
    Crop: "Rice",
    Area: 80.0,
    Production: 240.0,
  },
  {
    State_Name: "Chhattisgarh",
    District_Name: "BALOD",
    Crop_Year: 2011,
    Season: "Kharif",
    Crop: "Arhar\\/Tur",
    Area: 607.0,
    Production: 290.0,
  },
  {
    State_Name: "Chhattisgarh",
    District_Name: "BALOD",
    Crop_Year: 2011,
    Season: "Kharif",
    Crop: "Horse-gram",
    Area: 288.0,
    Production: 102.0,
  },
  {
    State_Name: "Chhattisgarh",
    District_Name: "BALOD",
    Crop_Year: 2011,
    Season: "Kharif",
    Crop: "Jowar",
    Area: 11.0,
    Production: 8.0,
  },
  {
    State_Name: "Chhattisgarh",
    District_Name: "BALOD",
    Crop_Year: 2011,
    Season: "Kharif",
    Crop: "Maize",
    Area: 125.0,
    Production: 149.0,
  },
  {
    State_Name: "Chhattisgarh",
    District_Name: "BALOD",
    Crop_Year: 2011,
    Season: "Kharif",
    Crop: "Mesta",
    Area: 8.0,
    Production: 15.0,
  },
  {
    State_Name: "Chhattisgarh",
    District_Name: "BALOD",
    Crop_Year: 2011,
    Season: "Kharif",
    Crop: "Moong(Green Gram)",
    Area: 46.0,
    Production: 12.0,
  },
  {
    State_Name: "Chhattisgarh",
    District_Name: "BALOD",
    Crop_Year: 2011,
    Season: "Kharif",
    Crop: "Other Kharif pulses",
    Area: 218.0,
    Production: 1.0,
  },
  {
    State_Name: "Chhattisgarh",
    District_Name: "BALOD",
    Crop_Year: 2011,
    Season: "Kharif",
    Crop: "Ragi",
    Area: 4.0,
    Production: 1.0,
  },
  {
    State_Name: "Chhattisgarh",
    District_Name: "BALOD",
    Crop_Year: 2011,
    Season: "Kharif",
    Crop: "Rice",
    Area: 177115.0,
    Production: 327525.0,
  },
  {
    State_Name: "Chhattisgarh",
    District_Name: "BALOD",
    Crop_Year: 2011,
    Season: "Kharif",
    Crop: "Sesamum",
    Area: 291.0,
    Production: 111.0,
  },
  {
    State_Name: "Chhattisgarh",
    District_Name: "BALOD",
    Crop_Year: 2011,
    Season: "Kharif",
    Crop: "Small millets",
    Area: 1448.0,
    Production: 203.0,
  },
  {
    State_Name: "Chhattisgarh",
    District_Name: "BALOD",
    Crop_Year: 2011,
    Season: "Kharif",
    Crop: "Soyabean",
    Area: 136.0,
    Production: 101.0,
  },
  {
    State_Name: "Chhattisgarh",
    District_Name: "BALOD",
    Crop_Year: 2011,
    Season: "Kharif",
    Crop: "Sunflower",
    Area: 37.0,
    Production: 36.0,
  },
  {
    State_Name: "Chhattisgarh",
    District_Name: "BALOD",
    Crop_Year: 2011,
    Season: "Kharif",
    Crop: "Urad",
    Area: 1261.0,
    Production: 383.0,
  },
  {
    State_Name: "Chhattisgarh",
    District_Name: "BALOD",
    Crop_Year: 2011,
    Season: "Rabi",
    Crop: "Barley",
    Area: 3.0,
    Production: 3.0,
  },
  {
    State_Name: "Dadra and Nagar Haveli",
    District_Name: "DADRA AND NAGAR HAVELI",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Arhar\\/Tur",
    Area: 1624.0,
    Production: 1440.0,
  },
  {
    State_Name: "Dadra and Nagar Haveli",
    District_Name: "DADRA AND NAGAR HAVELI",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Coconut",
    Area: 175.0,
    Production: 64750.0,
  },
  {
    State_Name: "Dadra and Nagar Haveli",
    District_Name: "DADRA AND NAGAR HAVELI",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Groundnut",
    Area: 20.0,
    Production: 40.0,
  },
  {
    State_Name: "Dadra and Nagar Haveli",
    District_Name: "DADRA AND NAGAR HAVELI",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Jowar",
    Area: 523.0,
    Production: 418.0,
  },
  {
    State_Name: "Dadra and Nagar Haveli",
    District_Name: "DADRA AND NAGAR HAVELI",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Maize",
    Area: 16.0,
    Production: 10.0,
  },
  {
    State_Name: "Dadra and Nagar Haveli",
    District_Name: "DADRA AND NAGAR HAVELI",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Niger seed",
    Area: 180.0,
    Production: 103.0,
  },
  {
    State_Name: "Dadra and Nagar Haveli",
    District_Name: "DADRA AND NAGAR HAVELI",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Other Kharif pulses",
    Area: 1351.0,
    Production: 1198.0,
  },
  {
    State_Name: "Dadra and Nagar Haveli",
    District_Name: "DADRA AND NAGAR HAVELI",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Ragi",
    Area: 1669.0,
    Production: 2166.0,
  },
  {
    State_Name: "Dadra and Nagar Haveli",
    District_Name: "DADRA AND NAGAR HAVELI",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Rice",
    Area: 14123.0,
    Production: 24023.0,
  },
  {
    State_Name: "Dadra and Nagar Haveli",
    District_Name: "DADRA AND NAGAR HAVELI",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Sannhamp",
    Area: 25.0,
    Production: 15.0,
  },
  {
    State_Name: "Dadra and Nagar Haveli",
    District_Name: "DADRA AND NAGAR HAVELI",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Small millets",
    Area: 226.0,
    Production: 181.0,
  },
  {
    State_Name: "Dadra and Nagar Haveli",
    District_Name: "DADRA AND NAGAR HAVELI",
    Crop_Year: 1998,
    Season: "Rabi",
    Crop: "Other  Rabi pulses",
    Area: 2600.0,
    Production: 2080.0,
  },
  {
    State_Name: "Dadra and Nagar Haveli",
    District_Name: "DADRA AND NAGAR HAVELI",
    Crop_Year: 1998,
    Season: "Rabi",
    Crop: "Rice",
    Area: 383.0,
    Production: 770.0,
  },
  {
    State_Name: "Dadra and Nagar Haveli",
    District_Name: "DADRA AND NAGAR HAVELI",
    Crop_Year: 1998,
    Season: "Winter",
    Crop: "Banana",
    Area: 14.0,
    Production: 280.0,
  },
  {
    State_Name: "Dadra and Nagar Haveli",
    District_Name: "DADRA AND NAGAR HAVELI",
    Crop_Year: 1998,
    Season: "Winter",
    Crop: "Coriander",
    Area: 5.0,
    Production: 4.0,
  },
  {
    State_Name: "Goa",
    District_Name: "NORTH GOA",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Groundnut",
    Area: 310.0,
    Production: 376.0,
  },
  {
    State_Name: "Goa",
    District_Name: "NORTH GOA",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Other Kharif pulses",
    Area: 760.0,
    Production: 49.0,
  },
  {
    State_Name: "Goa",
    District_Name: "NORTH GOA",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Groundnut",
    Area: 829.0,
    Production: 1601.0,
  },
  {
    State_Name: "Goa",
    District_Name: "NORTH GOA",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Other  Rabi pulses",
    Area: 7369.0,
    Production: 6241.0,
  },
  {
    State_Name: "Goa",
    District_Name: "NORTH GOA",
    Crop_Year: 1997,
    Season: "Whole Year",
    Crop: "Ragi",
    Area: 1675.0,
    Production: 1572.0,
  },
  {
    State_Name: "Goa",
    District_Name: "NORTH GOA",
    Crop_Year: 2004,
    Season: "Kharif",
    Crop: "Groundnut",
    Area: 3204.0,
    Production: 5234.0,
  },
  {
    State_Name: "Goa",
    District_Name: "NORTH GOA",
    Crop_Year: 2004,
    Season: "Kharif",
    Crop: "Ragi",
    Area: 160.0,
    Production: 165.0,
  },
  {
    State_Name: "Goa",
    District_Name: "NORTH GOA",
    Crop_Year: 2004,
    Season: "Kharif",
    Crop: "Rice",
    Area: 29535.0,
    Production: 85664.0,
  },
  {
    State_Name: "Goa",
    District_Name: "NORTH GOA",
    Crop_Year: 2004,
    Season: "Whole Year",
    Crop: "Black pepper",
    Area: 334.0,
    Production: 55.0,
  },
  {
    State_Name: "Goa",
    District_Name: "NORTH GOA",
    Crop_Year: 2004,
    Season: "Whole Year",
    Crop: "Cashewnut",
    Area: 39987.0,
    Production: 18714.0,
  },
  {
    State_Name: "Goa",
    District_Name: "NORTH GOA",
    Crop_Year: 2004,
    Season: "Whole Year",
    Crop: "Coconut",
    Area: 11083.0,
    Production: 54410000.0,
  },
  {
    State_Name: "Goa",
    District_Name: "NORTH GOA",
    Crop_Year: 2004,
    Season: "Whole Year",
    Crop: "Sugarcane",
    Area: 295.0,
    Production: 17103.0,
  },
  {
    State_Name: "Goa",
    District_Name: "NORTH GOA",
    Crop_Year: 2005,
    Season: "Kharif",
    Crop: "Groundnut",
    Area: 3281.0,
    Production: 7891.0,
  },
  {
    State_Name: "Goa",
    District_Name: "NORTH GOA",
    Crop_Year: 2005,
    Season: "Kharif",
    Crop: "Ragi",
    Area: 223.0,
    Production: 279.0,
  },
  {
    State_Name: "Goa",
    District_Name: "NORTH GOA",
    Crop_Year: 2005,
    Season: "Kharif",
    Crop: "Rice",
    Area: 29605.0,
    Production: 85399.0,
  },
  {
    State_Name: "Gujarat",
    District_Name: "AHMADABAD",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Arhar\\/Tur",
    Area: 2900.0,
    Production: 2200.0,
  },
  {
    State_Name: "Gujarat",
    District_Name: "AHMADABAD",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Bajra",
    Area: 41700.0,
    Production: 43700.0,
  },
  {
    State_Name: "Gujarat",
    District_Name: "AHMADABAD",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Dry chillies",
    Area: 700.0,
    Production: 700.0,
  },
  {
    State_Name: "Gujarat",
    District_Name: "AHMADABAD",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Groundnut",
    Area: 500.0,
    Production: 600.0,
  },
  {
    State_Name: "Gujarat",
    District_Name: "AHMADABAD",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Jowar",
    Area: 42500.0,
    Production: 33500.0,
  },
  {
    State_Name: "Gujarat",
    District_Name: "AHMADABAD",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Moong(Green Gram)",
    Area: 2300.0,
    Production: 1200.0,
  },
  {
    State_Name: "Gujarat",
    District_Name: "AHMADABAD",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Moth",
    Area: 100.0,
    Production: 100.0,
  },
  {
    State_Name: "Gujarat",
    District_Name: "AHMADABAD",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Other Kharif pulses",
    Area: 400.0,
    Production: 200.0,
  },
  {
    State_Name: "Gujarat",
    District_Name: "AHMADABAD",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Urad",
    Area: 1300.0,
    Production: 1100.0,
  },
  {
    State_Name: "Gujarat",
    District_Name: "AHMADABAD",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Gram",
    Area: 14400.0,
    Production: 7200.0,
  },
  {
    State_Name: "Gujarat",
    District_Name: "AHMADABAD",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Jowar",
    Area: 2000.0,
    Production: 1700.0,
  },
  {
    State_Name: "Gujarat",
    District_Name: "AHMADABAD",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Rapeseed &Mustard",
    Area: 9000.0,
    Production: 9400.0,
  },
  {
    State_Name: "Gujarat",
    District_Name: "AHMADABAD",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Wheat",
    Area: 96000.0,
    Production: 121400.0,
  },
  {
    State_Name: "Gujarat",
    District_Name: "AHMADABAD",
    Crop_Year: 1997,
    Season: "Summer",
    Crop: "Bajra",
    Area: 12200.0,
    Production: 26300.0,
  },
  {
    State_Name: "Gujarat",
    District_Name: "AHMADABAD",
    Crop_Year: 1997,
    Season: "Summer",
    Crop: "Groundnut",
    Area: 100.0,
    Production: 100.0,
  },
  {
    State_Name: "Haryana",
    District_Name: "AMBALA",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Bajra",
    Area: 1000.0,
    Production: 1000.0,
  },
  {
    State_Name: "Haryana",
    District_Name: "AMBALA",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Maize",
    Area: 8000.0,
    Production: 15000.0,
  },
  {
    State_Name: "Haryana",
    District_Name: "AMBALA",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Other Kharif pulses",
    Area: 1000.0,
    Production: 600.0,
  },
  {
    State_Name: "Haryana",
    District_Name: "AMBALA",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Rice",
    Area: 65000.0,
    Production: 182000.0,
  },
  {
    State_Name: "Haryana",
    District_Name: "AMBALA",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Other  Rabi pulses",
    Area: 25000.0,
    Production: 18000.0,
  },
  {
    State_Name: "Haryana",
    District_Name: "AMBALA",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Wheat",
    Area: 72000.0,
    Production: 226000.0,
  },
  {
    State_Name: "Haryana",
    District_Name: "AMBALA",
    Crop_Year: 1997,
    Season: "Whole Year",
    Crop: "Sugarcane",
    Area: 12000.0,
    Production: 580000.0,
  },
  {
    State_Name: "Haryana",
    District_Name: "AMBALA",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Arhar\\/Tur",
    Area: 130.0,
    Production: 200.0,
  },
  {
    State_Name: "Haryana",
    District_Name: "AMBALA",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Bajra",
    Area: 370.0,
    Production: null,
  },
  {
    State_Name: "Haryana",
    District_Name: "AMBALA",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Cotton(lint)",
    Area: 25.0,
    Production: null,
  },
  {
    State_Name: "Haryana",
    District_Name: "AMBALA",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Groundnut",
    Area: 17.0,
    Production: null,
  },
  {
    State_Name: "Haryana",
    District_Name: "AMBALA",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Jowar",
    Area: 1.0,
    Production: null,
  },
  {
    State_Name: "Haryana",
    District_Name: "AMBALA",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Maize",
    Area: 5610.0,
    Production: 11000.0,
  },
  {
    State_Name: "Haryana",
    District_Name: "AMBALA",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Moth",
    Area: 1.0,
    Production: null,
  },
  {
    State_Name: "Haryana",
    District_Name: "AMBALA",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Rice",
    Area: 71365.0,
    Production: 186000.0,
  },
  {
    State_Name: "Himachal Pradesh",
    District_Name: "BILASPUR",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Arhar\\/Tur",
    Area: 4.0,
    Production: 1.0,
  },
  {
    State_Name: "Himachal Pradesh",
    District_Name: "BILASPUR",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Bajra",
    Area: 3.0,
    Production: 2.0,
  },
  {
    State_Name: "Himachal Pradesh",
    District_Name: "BILASPUR",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Groundnut",
    Area: 3.0,
    Production: 1.0,
  },
  {
    State_Name: "Himachal Pradesh",
    District_Name: "BILASPUR",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Horse-gram",
    Area: 40.0,
    Production: 23.0,
  },
  {
    State_Name: "Himachal Pradesh",
    District_Name: "BILASPUR",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Maize",
    Area: 24483.0,
    Production: 42167.0,
  },
  {
    State_Name: "Himachal Pradesh",
    District_Name: "BILASPUR",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Rice",
    Area: 2068.0,
    Production: 2584.0,
  },
  {
    State_Name: "Himachal Pradesh",
    District_Name: "BILASPUR",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Sesamum",
    Area: 133.0,
    Production: 54.0,
  },
  {
    State_Name: "Himachal Pradesh",
    District_Name: "BILASPUR",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Small millets",
    Area: 1.0,
    Production: null,
  },
  {
    State_Name: "Himachal Pradesh",
    District_Name: "BILASPUR",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Soyabean",
    Area: 12.0,
    Production: 8.0,
  },
  {
    State_Name: "Himachal Pradesh",
    District_Name: "BILASPUR",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Urad",
    Area: 170.0,
    Production: 96.0,
  },
  {
    State_Name: "Himachal Pradesh",
    District_Name: "BILASPUR",
    Crop_Year: 1998,
    Season: "Rabi",
    Crop: "Barley",
    Area: 317.0,
    Production: 329.0,
  },
  {
    State_Name: "Himachal Pradesh",
    District_Name: "BILASPUR",
    Crop_Year: 1998,
    Season: "Rabi",
    Crop: "Gram",
    Area: 196.0,
    Production: 167.0,
  },
  {
    State_Name: "Himachal Pradesh",
    District_Name: "BILASPUR",
    Crop_Year: 1998,
    Season: "Rabi",
    Crop: "Masoor",
    Area: 12.0,
    Production: 4.0,
  },
  {
    State_Name: "Himachal Pradesh",
    District_Name: "BILASPUR",
    Crop_Year: 1998,
    Season: "Rabi",
    Crop: "Potato",
    Area: 13.0,
    Production: 153.0,
  },
  {
    State_Name: "Himachal Pradesh",
    District_Name: "BILASPUR",
    Crop_Year: 1998,
    Season: "Rabi",
    Crop: "Rapeseed &Mustard",
    Area: 365.0,
    Production: 141.0,
  },
  {
    State_Name: "Jammu and Kashmir",
    District_Name: "ANANTNAG",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Maize",
    Area: 21291.0,
    Production: 19100.0,
  },
  {
    State_Name: "Jammu and Kashmir",
    District_Name: "ANANTNAG",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Rice",
    Area: 41279.0,
    Production: 1105.0,
  },
  {
    State_Name: "Jammu and Kashmir",
    District_Name: "ANANTNAG",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Wheat",
    Area: 23.0,
    Production: 20.0,
  },
  {
    State_Name: "Jammu and Kashmir",
    District_Name: "ANANTNAG",
    Crop_Year: 1999,
    Season: "Kharif",
    Crop: "Cond-spcs other",
    Area: 38.0,
    Production: 38.0,
  },
  {
    State_Name: "Jammu and Kashmir",
    District_Name: "ANANTNAG",
    Crop_Year: 1999,
    Season: "Kharif",
    Crop: "Maize",
    Area: 22099.0,
    Production: 12830.0,
  },
  {
    State_Name: "Jammu and Kashmir",
    District_Name: "ANANTNAG",
    Crop_Year: 1999,
    Season: "Kharif",
    Crop: "Rice",
    Area: 40380.0,
    Production: 90749.1,
  },
  {
    State_Name: "Jammu and Kashmir",
    District_Name: "ANANTNAG",
    Crop_Year: 1999,
    Season: "Rabi",
    Crop: "Rapeseed &Mustard",
    Area: 24080.0,
    Production: 22199.3,
  },
  {
    State_Name: "Jammu and Kashmir",
    District_Name: "ANANTNAG",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Maize",
    Area: 25686.0,
    Production: 31810.0,
  },
  {
    State_Name: "Jammu and Kashmir",
    District_Name: "ANANTNAG",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Rice",
    Area: 37577.0,
    Production: 69551.8,
  },
  {
    State_Name: "Jammu and Kashmir",
    District_Name: "ANANTNAG",
    Crop_Year: 2000,
    Season: "Rabi",
    Crop: "Rapeseed &Mustard",
    Area: 24063.0,
    Production: 8806.0,
  },
  {
    State_Name: "Jammu and Kashmir",
    District_Name: "ANANTNAG",
    Crop_Year: 2000,
    Season: "Rabi",
    Crop: "Wheat",
    Area: 7.0,
    Production: 10.0,
  },
  {
    State_Name: "Jammu and Kashmir",
    District_Name: "ANANTNAG",
    Crop_Year: 2000,
    Season: "Whole Year",
    Crop: "Dry chillies",
    Area: 31.0,
    Production: 37.0,
  },
  {
    State_Name: "Jammu and Kashmir",
    District_Name: "ANANTNAG",
    Crop_Year: 2001,
    Season: "Kharif",
    Crop: "Maize",
    Area: 23725.0,
    Production: 23820.0,
  },
  {
    State_Name: "Jammu and Kashmir",
    District_Name: "ANANTNAG",
    Crop_Year: 2001,
    Season: "Kharif",
    Crop: "Moong(Green Gram)",
    Area: 686.0,
    Production: 354.0,
  },
  {
    State_Name: "Jammu and Kashmir",
    District_Name: "ANANTNAG",
    Crop_Year: 2001,
    Season: "Kharif",
    Crop: "Rice",
    Area: 38893.0,
    Production: 56910.0,
  },
  {
    State_Name: "Jharkhand",
    District_Name: "BOKARO",
    Crop_Year: 2002,
    Season: "Autumn",
    Crop: "Maize",
    Area: 1589.28,
    Production: 2223.4,
  },
  {
    State_Name: "Jharkhand",
    District_Name: "BOKARO",
    Crop_Year: 2002,
    Season: "Rabi",
    Crop: "Wheat",
    Area: 1760.13,
    Production: 1960.07,
  },
  {
    State_Name: "Jharkhand",
    District_Name: "BOKARO",
    Crop_Year: 2002,
    Season: "Winter",
    Crop: "Rice",
    Area: 31891.35,
    Production: 22642.85,
  },
  {
    State_Name: "Jharkhand",
    District_Name: "BOKARO",
    Crop_Year: 2003,
    Season: "Autumn",
    Crop: "Maize",
    Area: 1589.92,
    Production: 1901.54,
  },
  {
    State_Name: "Jharkhand",
    District_Name: "BOKARO",
    Crop_Year: 2003,
    Season: "Rabi",
    Crop: "Wheat",
    Area: 1383.93,
    Production: 957.68,
  },
  {
    State_Name: "Jharkhand",
    District_Name: "BOKARO",
    Crop_Year: 2003,
    Season: "Winter",
    Crop: "Rice",
    Area: 31904.26,
    Production: 29990.01,
  },
  {
    State_Name: "Jharkhand",
    District_Name: "BOKARO",
    Crop_Year: 2004,
    Season: "Autumn",
    Crop: "Maize",
    Area: 2070.85,
    Production: 2563.71,
  },
  {
    State_Name: "Jharkhand",
    District_Name: "BOKARO",
    Crop_Year: 2004,
    Season: "Rabi",
    Crop: "Gram",
    Area: 165.53,
    Production: 142.02,
  },
  {
    State_Name: "Jharkhand",
    District_Name: "BOKARO",
    Crop_Year: 2004,
    Season: "Rabi",
    Crop: "Rapeseed &Mustard",
    Area: 80.48,
    Production: 72.51,
  },
  {
    State_Name: "Jharkhand",
    District_Name: "BOKARO",
    Crop_Year: 2004,
    Season: "Rabi",
    Crop: "Wheat",
    Area: 1231.39,
    Production: 1435.8,
  },
  {
    State_Name: "Jharkhand",
    District_Name: "BOKARO",
    Crop_Year: 2004,
    Season: "Winter",
    Crop: "Rice",
    Area: 16103.97,
    Production: 10897.03,
  },
  {
    State_Name: "Jharkhand",
    District_Name: "BOKARO",
    Crop_Year: 2005,
    Season: "Autumn",
    Crop: "Maize",
    Area: 1675.32,
    Production: 934.83,
  },
  {
    State_Name: "Jharkhand",
    District_Name: "BOKARO",
    Crop_Year: 2005,
    Season: "Rabi",
    Crop: "Gram",
    Area: 32.97,
    Production: 23.54,
  },
  {
    State_Name: "Jharkhand",
    District_Name: "BOKARO",
    Crop_Year: 2005,
    Season: "Rabi",
    Crop: "Potato",
    Area: 458.18,
    Production: 5928.39,
  },
  {
    State_Name: "Jharkhand",
    District_Name: "BOKARO",
    Crop_Year: 2005,
    Season: "Rabi",
    Crop: "Rapeseed &Mustard",
    Area: 31.19,
    Production: 7.7,
  },
  {
    State_Name: "Karnataka",
    District_Name: "BAGALKOT",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Arhar\\/Tur",
    Area: 6154.0,
    Production: 2602.0,
  },
  {
    State_Name: "Karnataka",
    District_Name: "BAGALKOT",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Bajra",
    Area: 48855.0,
    Production: 52375.0,
  },
  {
    State_Name: "Karnataka",
    District_Name: "BAGALKOT",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Castor seed",
    Area: 71.0,
    Production: 61.0,
  },
  {
    State_Name: "Karnataka",
    District_Name: "BAGALKOT",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Cotton(lint)",
    Area: 15225.0,
    Production: 22129.0,
  },
  {
    State_Name: "Karnataka",
    District_Name: "BAGALKOT",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Groundnut",
    Area: 16368.0,
    Production: 7734.0,
  },
  {
    State_Name: "Karnataka",
    District_Name: "BAGALKOT",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Horse-gram",
    Area: 3372.0,
    Production: 1156.0,
  },
  {
    State_Name: "Karnataka",
    District_Name: "BAGALKOT",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Jowar",
    Area: 12363.0,
    Production: 24855.0,
  },
  {
    State_Name: "Karnataka",
    District_Name: "BAGALKOT",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Maize",
    Area: 30630.0,
    Production: 92831.0,
  },
  {
    State_Name: "Karnataka",
    District_Name: "BAGALKOT",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Moong(Green Gram)",
    Area: 13872.0,
    Production: 1147.0,
  },
  {
    State_Name: "Karnataka",
    District_Name: "BAGALKOT",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Niger seed",
    Area: 310.0,
    Production: 47.0,
  },
  {
    State_Name: "Karnataka",
    District_Name: "BAGALKOT",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Onion",
    Area: 3090.0,
    Production: 14100.0,
  },
  {
    State_Name: "Karnataka",
    District_Name: "BAGALKOT",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Rapeseed &Mustard",
    Area: 51.0,
    Production: 7.0,
  },
  {
    State_Name: "Karnataka",
    District_Name: "BAGALKOT",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Rice",
    Area: 197.0,
    Production: 316.0,
  },
  {
    State_Name: "Karnataka",
    District_Name: "BAGALKOT",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Sesamum",
    Area: 2395.0,
    Production: 937.0,
  },
  {
    State_Name: "Karnataka",
    District_Name: "BAGALKOT",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Soyabean",
    Area: 5221.0,
    Production: 3854.0,
  },
  {
    State_Name: "Kerala",
    District_Name: "ALAPPUZHA",
    Crop_Year: 1997,
    Season: "Whole Year",
    Crop: "Arecanut",
    Area: 2253.0,
    Production: 1518.0,
  },
  {
    State_Name: "Kerala",
    District_Name: "ALAPPUZHA",
    Crop_Year: 1997,
    Season: "Whole Year",
    Crop: "Black pepper",
    Area: 2235.0,
    Production: 248.0,
  },
  {
    State_Name: "Kerala",
    District_Name: "ALAPPUZHA",
    Crop_Year: 1997,
    Season: "Whole Year",
    Crop: "Cashewnut",
    Area: 7205.0,
    Production: 2358.0,
  },
  {
    State_Name: "Kerala",
    District_Name: "ALAPPUZHA",
    Crop_Year: 1997,
    Season: "Whole Year",
    Crop: "Coconut",
    Area: 77893.0,
    Production: 399000.0,
  },
  {
    State_Name: "Kerala",
    District_Name: "ALAPPUZHA",
    Crop_Year: 1997,
    Season: "Whole Year",
    Crop: "Tapioca",
    Area: 3911.0,
    Production: 74110.0,
  },
  {
    State_Name: "Kerala",
    District_Name: "ALAPPUZHA",
    Crop_Year: 1998,
    Season: "Autumn",
    Crop: "Rice",
    Area: 8719.0,
    Production: 17570.0,
  },
  {
    State_Name: "Kerala",
    District_Name: "ALAPPUZHA",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Sesamum",
    Area: 1150.0,
    Production: 140.0,
  },
  {
    State_Name: "Kerala",
    District_Name: "ALAPPUZHA",
    Crop_Year: 1998,
    Season: "Summer",
    Crop: "Rice",
    Area: 19058.0,
    Production: 58013.0,
  },
  {
    State_Name: "Kerala",
    District_Name: "ALAPPUZHA",
    Crop_Year: 1998,
    Season: "Whole Year",
    Crop: "Arecanut",
    Area: 2067.0,
    Production: 766.0,
  },
  {
    State_Name: "Kerala",
    District_Name: "ALAPPUZHA",
    Crop_Year: 1998,
    Season: "Whole Year",
    Crop: "Banana",
    Area: 324.0,
    Production: 4493.0,
  },
  {
    State_Name: "Kerala",
    District_Name: "ALAPPUZHA",
    Crop_Year: 1998,
    Season: "Whole Year",
    Crop: "Black pepper",
    Area: 2028.0,
    Production: 256.0,
  },
  {
    State_Name: "Kerala",
    District_Name: "ALAPPUZHA",
    Crop_Year: 1998,
    Season: "Whole Year",
    Crop: "Cashewnut",
    Area: 4860.0,
    Production: 792.0,
  },
  {
    State_Name: "Kerala",
    District_Name: "ALAPPUZHA",
    Crop_Year: 1998,
    Season: "Whole Year",
    Crop: "Coconut",
    Area: 58621.0,
    Production: 288000000.0,
  },
  {
    State_Name: "Kerala",
    District_Name: "ALAPPUZHA",
    Crop_Year: 1998,
    Season: "Whole Year",
    Crop: "Dry ginger",
    Area: 119.0,
    Production: 224.0,
  },
  {
    State_Name: "Kerala",
    District_Name: "ALAPPUZHA",
    Crop_Year: 1998,
    Season: "Whole Year",
    Crop: "Sugarcane",
    Area: 192.0,
    Production: 4190.0,
  },
  {
    State_Name: "Madhya Pradesh",
    District_Name: "AGAR MALWA",
    Crop_Year: 2013,
    Season: "Kharif",
    Crop: "Arhar\\/Tur",
    Area: 1834.0,
    Production: 739.0,
  },
  {
    State_Name: "Madhya Pradesh",
    District_Name: "AGAR MALWA",
    Crop_Year: 2013,
    Season: "Kharif",
    Crop: "Bajra",
    Area: 5.0,
    Production: 4.0,
  },
  {
    State_Name: "Madhya Pradesh",
    District_Name: "AGAR MALWA",
    Crop_Year: 2013,
    Season: "Kharif",
    Crop: "Barley",
    Area: 286.0,
    Production: 466.0,
  },
  {
    State_Name: "Madhya Pradesh",
    District_Name: "AGAR MALWA",
    Crop_Year: 2013,
    Season: "Kharif",
    Crop: "Groundnut",
    Area: 1077.0,
    Production: 1138.0,
  },
  {
    State_Name: "Madhya Pradesh",
    District_Name: "AGAR MALWA",
    Crop_Year: 2013,
    Season: "Kharif",
    Crop: "Jowar",
    Area: 2750.0,
    Production: 3347.0,
  },
  {
    State_Name: "Madhya Pradesh",
    District_Name: "AGAR MALWA",
    Crop_Year: 2013,
    Season: "Kharif",
    Crop: "Maize",
    Area: 15270.0,
    Production: 16578.0,
  },
  {
    State_Name: "Madhya Pradesh",
    District_Name: "AGAR MALWA",
    Crop_Year: 2013,
    Season: "Kharif",
    Crop: "Moong(Green Gram)",
    Area: 424.0,
    Production: 143.0,
  },
  {
    State_Name: "Madhya Pradesh",
    District_Name: "AGAR MALWA",
    Crop_Year: 2013,
    Season: "Kharif",
    Crop: "Other Kharif pulses",
    Area: 55.0,
    Production: 3.0,
  },
  {
    State_Name: "Madhya Pradesh",
    District_Name: "AGAR MALWA",
    Crop_Year: 2013,
    Season: "Kharif",
    Crop: "Rice",
    Area: 2.0,
    Production: 1.0,
  },
  {
    State_Name: "Madhya Pradesh",
    District_Name: "AGAR MALWA",
    Crop_Year: 2013,
    Season: "Kharif",
    Crop: "Sannhamp",
    Area: 21.0,
    Production: 50.0,
  },
  {
    State_Name: "Madhya Pradesh",
    District_Name: "AGAR MALWA",
    Crop_Year: 2013,
    Season: "Kharif",
    Crop: "Soyabean",
    Area: 137322.0,
    Production: 80718.0,
  },
  {
    State_Name: "Madhya Pradesh",
    District_Name: "AGAR MALWA",
    Crop_Year: 2013,
    Season: "Kharif",
    Crop: "Urad",
    Area: 1892.0,
    Production: 687.0,
  },
  {
    State_Name: "Madhya Pradesh",
    District_Name: "AGAR MALWA",
    Crop_Year: 2013,
    Season: "Rabi",
    Crop: "Gram",
    Area: 41916.0,
    Production: 27026.0,
  },
  {
    State_Name: "Madhya Pradesh",
    District_Name: "AGAR MALWA",
    Crop_Year: 2013,
    Season: "Rabi",
    Crop: "Linseed",
    Area: 33.0,
    Production: 25.0,
  },
  {
    State_Name: "Madhya Pradesh",
    District_Name: "AGAR MALWA",
    Crop_Year: 2013,
    Season: "Rabi",
    Crop: "Masoor",
    Area: 7170.0,
    Production: 3886.0,
  },
  {
    State_Name: "Maharashtra",
    District_Name: "AHMEDNAGAR",
    Crop_Year: 1997,
    Season: "Autumn",
    Crop: "Maize",
    Area: 1.0,
    Production: 1113.0,
  },
  {
    State_Name: "Maharashtra",
    District_Name: "AHMEDNAGAR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Arhar\\/Tur",
    Area: 17600.0,
    Production: 6300.0,
  },
  {
    State_Name: "Maharashtra",
    District_Name: "AHMEDNAGAR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Bajra",
    Area: 274100.0,
    Production: 152800.0,
  },
  {
    State_Name: "Maharashtra",
    District_Name: "AHMEDNAGAR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Gram",
    Area: 40800.0,
    Production: 18600.0,
  },
  {
    State_Name: "Maharashtra",
    District_Name: "AHMEDNAGAR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Jowar",
    Area: 900.0,
    Production: 1100.0,
  },
  {
    State_Name: "Maharashtra",
    District_Name: "AHMEDNAGAR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Maize",
    Area: 4400.0,
    Production: 4700.0,
  },
  {
    State_Name: "Maharashtra",
    District_Name: "AHMEDNAGAR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Moong(Green Gram)",
    Area: 10200.0,
    Production: 900.0,
  },
  {
    State_Name: "Maharashtra",
    District_Name: "AHMEDNAGAR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Pulses total",
    Area: 451.0,
    Production: 130.0,
  },
  {
    State_Name: "Maharashtra",
    District_Name: "AHMEDNAGAR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Ragi",
    Area: 2600.0,
    Production: 2100.0,
  },
  {
    State_Name: "Maharashtra",
    District_Name: "AHMEDNAGAR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Rice",
    Area: 5900.0,
    Production: 7200.0,
  },
  {
    State_Name: "Maharashtra",
    District_Name: "AHMEDNAGAR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Sugarcane",
    Area: 45900.0,
    Production: 38940.0,
  },
  {
    State_Name: "Maharashtra",
    District_Name: "AHMEDNAGAR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Total foodgrain",
    Area: 3384.0,
    Production: 1836.0,
  },
  {
    State_Name: "Maharashtra",
    District_Name: "AHMEDNAGAR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Urad",
    Area: 1600.0,
    Production: 800.0,
  },
  {
    State_Name: "Maharashtra",
    District_Name: "AHMEDNAGAR",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Jowar",
    Area: 598400.0,
    Production: 217000.0,
  },
  {
    State_Name: "Maharashtra",
    District_Name: "AHMEDNAGAR",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Maize",
    Area: 6200.0,
    Production: 9100.0,
  },
  {
    State_Name: "Manipur",
    District_Name: "BISHNUPUR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Onion",
    Area: 2.0,
    Production: 5.0,
  },
  {
    State_Name: "Manipur",
    District_Name: "BISHNUPUR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Rice",
    Area: 17.0,
    Production: 40.0,
  },
  {
    State_Name: "Manipur",
    District_Name: "BISHNUPUR",
    Crop_Year: 1997,
    Season: "Whole Year",
    Crop: "Sugarcane",
    Area: 7.0,
    Production: 2.0,
  },
  {
    State_Name: "Manipur",
    District_Name: "BISHNUPUR",
    Crop_Year: 1998,
    Season: "Autumn",
    Crop: "Dry chillies",
    Area: 160.0,
    Production: 100.0,
  },
  {
    State_Name: "Manipur",
    District_Name: "BISHNUPUR",
    Crop_Year: 1998,
    Season: "Autumn",
    Crop: "Jute",
    Area: 10.0,
    Production: 20.0,
  },
  {
    State_Name: "Manipur",
    District_Name: "BISHNUPUR",
    Crop_Year: 1998,
    Season: "Autumn",
    Crop: "Onion",
    Area: 10.0,
    Production: 20.0,
  },
  {
    State_Name: "Manipur",
    District_Name: "BISHNUPUR",
    Crop_Year: 1998,
    Season: "Autumn",
    Crop: "Rice",
    Area: 1470.0,
    Production: 3360.0,
  },
  {
    State_Name: "Manipur",
    District_Name: "BISHNUPUR",
    Crop_Year: 1998,
    Season: "Autumn",
    Crop: "Sugarcane",
    Area: 160.0,
    Production: 5230.0,
  },
  {
    State_Name: "Manipur",
    District_Name: "BISHNUPUR",
    Crop_Year: 1998,
    Season: "Autumn",
    Crop: "Turmeric",
    Area: 20.0,
    Production: 10.0,
  },
  {
    State_Name: "Manipur",
    District_Name: "BISHNUPUR",
    Crop_Year: 1998,
    Season: "Rabi",
    Crop: "Dry chillies",
    Area: 280.0,
    Production: 160.0,
  },
  {
    State_Name: "Manipur",
    District_Name: "BISHNUPUR",
    Crop_Year: 1998,
    Season: "Rabi",
    Crop: "Onion",
    Area: 10.0,
    Production: 20.0,
  },
  {
    State_Name: "Manipur",
    District_Name: "BISHNUPUR",
    Crop_Year: 1998,
    Season: "Rabi",
    Crop: "Peas & beans (Pulses)",
    Area: 60.0,
    Production: 30.0,
  },
  {
    State_Name: "Manipur",
    District_Name: "BISHNUPUR",
    Crop_Year: 1998,
    Season: "Rabi",
    Crop: "Potato",
    Area: 160.0,
    Production: 840.0,
  },
  {
    State_Name: "Manipur",
    District_Name: "BISHNUPUR",
    Crop_Year: 1998,
    Season: "Rabi",
    Crop: "Rapeseed &Mustard",
    Area: 440.0,
    Production: 200.0,
  },
  {
    State_Name: "Manipur",
    District_Name: "BISHNUPUR",
    Crop_Year: 1998,
    Season: "Rabi",
    Crop: "Sugarcane",
    Area: 10.0,
    Production: 330.0,
  },
  {
    State_Name: "Meghalaya",
    District_Name: "EAST GARO HILLS",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Arhar\\/Tur",
    Area: 111.0,
    Production: 95.0,
  },
  {
    State_Name: "Meghalaya",
    District_Name: "EAST GARO HILLS",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Cotton(lint)",
    Area: 2720.0,
    Production: 1960.0,
  },
  {
    State_Name: "Meghalaya",
    District_Name: "EAST GARO HILLS",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Dry ginger",
    Area: 3539.0,
    Production: 23163.0,
  },
  {
    State_Name: "Meghalaya",
    District_Name: "EAST GARO HILLS",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Jute",
    Area: 312.0,
    Production: 2916.0,
  },
  {
    State_Name: "Meghalaya",
    District_Name: "EAST GARO HILLS",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Maize",
    Area: 1090.0,
    Production: 1362.0,
  },
  {
    State_Name: "Meghalaya",
    District_Name: "EAST GARO HILLS",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Mesta",
    Area: 278.0,
    Production: 1354.0,
  },
  {
    State_Name: "Meghalaya",
    District_Name: "EAST GARO HILLS",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Rice",
    Area: 17301.0,
    Production: 22730.0,
  },
  {
    State_Name: "Meghalaya",
    District_Name: "EAST GARO HILLS",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Sesamum",
    Area: 295.0,
    Production: 147.0,
  },
  {
    State_Name: "Meghalaya",
    District_Name: "EAST GARO HILLS",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Small millets",
    Area: 494.0,
    Production: 415.0,
  },
  {
    State_Name: "Meghalaya",
    District_Name: "EAST GARO HILLS",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Soyabean",
    Area: 138.0,
    Production: 136.0,
  },
  {
    State_Name: "Meghalaya",
    District_Name: "EAST GARO HILLS",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Castor seed",
    Area: 11.0,
    Production: 5.0,
  },
  {
    State_Name: "Meghalaya",
    District_Name: "EAST GARO HILLS",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Gram",
    Area: 255.0,
    Production: 152.0,
  },
  {
    State_Name: "Meghalaya",
    District_Name: "EAST GARO HILLS",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Other  Rabi pulses",
    Area: 206.0,
    Production: 133.0,
  },
  {
    State_Name: "Meghalaya",
    District_Name: "EAST GARO HILLS",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Pulses total",
    Area: 572.0,
    Production: 380.0,
  },
  {
    State_Name: "Meghalaya",
    District_Name: "EAST GARO HILLS",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Rapeseed &Mustard",
    Area: 749.0,
    Production: 355.0,
  },
  {
    State_Name: "Mizoram",
    District_Name: "AIZAWL",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Arhar\\/Tur",
    Area: 48.0,
    Production: 69.0,
  },
  {
    State_Name: "Mizoram",
    District_Name: "AIZAWL",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Coconut",
    Area: 2.0,
    Production: 5.0,
  },
  {
    State_Name: "Mizoram",
    District_Name: "AIZAWL",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Groundnut",
    Area: 44.0,
    Production: 61.0,
  },
  {
    State_Name: "Mizoram",
    District_Name: "AIZAWL",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Kapas",
    Area: 263.0,
    Production: 246.0,
  },
  {
    State_Name: "Mizoram",
    District_Name: "AIZAWL",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Maize",
    Area: 4128.0,
    Production: 8141.0,
  },
  {
    State_Name: "Mizoram",
    District_Name: "AIZAWL",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Peas & beans (Pulses)",
    Area: 87.0,
    Production: 108.0,
  },
  {
    State_Name: "Mizoram",
    District_Name: "AIZAWL",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Rapeseed &Mustard",
    Area: 304.0,
    Production: 316.0,
  },
  {
    State_Name: "Mizoram",
    District_Name: "AIZAWL",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Sesamum",
    Area: 1368.0,
    Production: 1270.0,
  },
  {
    State_Name: "Mizoram",
    District_Name: "AIZAWL",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Soyabean",
    Area: 563.0,
    Production: 809.0,
  },
  {
    State_Name: "Mizoram",
    District_Name: "AIZAWL",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Rapeseed &Mustard",
    Area: 145.0,
    Production: 146.0,
  },
  {
    State_Name: "Mizoram",
    District_Name: "AIZAWL",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Tobacco",
    Area: 217.0,
    Production: 273.0,
  },
  {
    State_Name: "Mizoram",
    District_Name: "AIZAWL",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Wheat",
    Area: 22.0,
    Production: 11.0,
  },
  {
    State_Name: "Mizoram",
    District_Name: "AIZAWL",
    Crop_Year: 1997,
    Season: "Whole Year",
    Crop: "Rice",
    Area: 30274.0,
    Production: 50241.0,
  },
  {
    State_Name: "Mizoram",
    District_Name: "AIZAWL",
    Crop_Year: 1997,
    Season: "Whole Year",
    Crop: "Sugarcane",
    Area: 894.0,
    Production: 4890.0,
  },
  {
    State_Name: "Mizoram",
    District_Name: "AIZAWL",
    Crop_Year: 1997,
    Season: "Whole Year",
    Crop: "Tapioca",
    Area: 255.0,
    Production: 5981.0,
  },
  {
    State_Name: "Nagaland",
    District_Name: "DIMAPUR",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Arhar\\/Tur",
    Area: 700.0,
    Production: 690.0,
  },
  {
    State_Name: "Nagaland",
    District_Name: "DIMAPUR",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Bajra",
    Area: 190.0,
    Production: 160.0,
  },
  {
    State_Name: "Nagaland",
    District_Name: "DIMAPUR",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Castor seed",
    Area: 150.0,
    Production: 120.0,
  },
  {
    State_Name: "Nagaland",
    District_Name: "DIMAPUR",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Cotton(lint)",
    Area: 91.0,
    Production: 130.0,
  },
  {
    State_Name: "Nagaland",
    District_Name: "DIMAPUR",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Groundnut",
    Area: 650.0,
    Production: 670.0,
  },
  {
    State_Name: "Nagaland",
    District_Name: "DIMAPUR",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Jowar",
    Area: 270.0,
    Production: 230.0,
  },
  {
    State_Name: "Nagaland",
    District_Name: "DIMAPUR",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Jute",
    Area: 150.0,
    Production: 230.0,
  },
  {
    State_Name: "Nagaland",
    District_Name: "DIMAPUR",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Maize",
    Area: 4500.0,
    Production: 6800.0,
  },
  {
    State_Name: "Nagaland",
    District_Name: "DIMAPUR",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Moong(Green Gram)",
    Area: 280.0,
    Production: 230.0,
  },
  {
    State_Name: "Nagaland",
    District_Name: "DIMAPUR",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Niger seed",
    Area: 200.0,
    Production: 120.0,
  },
  {
    State_Name: "Nagaland",
    District_Name: "DIMAPUR",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Other Kharif pulses",
    Area: 660.0,
    Production: 760.0,
  },
  {
    State_Name: "Nagaland",
    District_Name: "DIMAPUR",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Rice",
    Area: 25740.0,
    Production: 45660.0,
  },
  {
    State_Name: "Nagaland",
    District_Name: "DIMAPUR",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Sesamum",
    Area: 460.0,
    Production: 520.0,
  },
  {
    State_Name: "Nagaland",
    District_Name: "DIMAPUR",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Small millets",
    Area: 1330.0,
    Production: 1600.0,
  },
  {
    State_Name: "Nagaland",
    District_Name: "DIMAPUR",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Soyabean",
    Area: 1420.0,
    Production: 2570.0,
  },
  {
    State_Name: "Odisha",
    District_Name: "ANUGUL",
    Crop_Year: 1997,
    Season: "Autumn",
    Crop: "Arhar\\/Tur",
    Area: 3555.0,
    Production: 739.0,
  },
  {
    State_Name: "Odisha",
    District_Name: "ANUGUL",
    Crop_Year: 1997,
    Season: "Autumn",
    Crop: "Groundnut",
    Area: 4086.0,
    Production: 4037.0,
  },
  {
    State_Name: "Odisha",
    District_Name: "ANUGUL",
    Crop_Year: 1997,
    Season: "Autumn",
    Crop: "Maize",
    Area: 948.0,
    Production: 675.0,
  },
  {
    State_Name: "Odisha",
    District_Name: "ANUGUL",
    Crop_Year: 1997,
    Season: "Autumn",
    Crop: "Paddy",
    Area: 21779.0,
    Production: 23578.0,
  },
  {
    State_Name: "Odisha",
    District_Name: "ANUGUL",
    Crop_Year: 1997,
    Season: "Autumn",
    Crop: "Ragi",
    Area: 46.0,
    Production: 25.0,
  },
  {
    State_Name: "Odisha",
    District_Name: "ANUGUL",
    Crop_Year: 1997,
    Season: "Autumn",
    Crop: "Sesamum",
    Area: 1307.0,
    Production: 385.0,
  },
  {
    State_Name: "Odisha",
    District_Name: "ANUGUL",
    Crop_Year: 1997,
    Season: "Autumn",
    Crop: "Urad",
    Area: 2878.0,
    Production: 547.0,
  },
  {
    State_Name: "Odisha",
    District_Name: "ANUGUL",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Wheat",
    Area: 94.0,
    Production: 67.0,
  },
  {
    State_Name: "Odisha",
    District_Name: "ANUGUL",
    Crop_Year: 1997,
    Season: "Summer",
    Crop: "Arhar\\/Tur",
    Area: 469.0,
    Production: 115.0,
  },
  {
    State_Name: "Odisha",
    District_Name: "ANUGUL",
    Crop_Year: 1997,
    Season: "Summer",
    Crop: "Groundnut",
    Area: 1022.0,
    Production: 1216.0,
  },
  {
    State_Name: "Odisha",
    District_Name: "ANUGUL",
    Crop_Year: 1997,
    Season: "Summer",
    Crop: "Maize",
    Area: 17.0,
    Production: 14.0,
  },
  {
    State_Name: "Odisha",
    District_Name: "ANUGUL",
    Crop_Year: 1997,
    Season: "Summer",
    Crop: "Paddy",
    Area: 4012.0,
    Production: 7184.0,
  },
  {
    State_Name: "Odisha",
    District_Name: "ANUGUL",
    Crop_Year: 1997,
    Season: "Summer",
    Crop: "Sesamum",
    Area: 790.0,
    Production: 187.0,
  },
  {
    State_Name: "Odisha",
    District_Name: "ANUGUL",
    Crop_Year: 1997,
    Season: "Summer",
    Crop: "Urad",
    Area: 15.0,
    Production: 4.0,
  },
  {
    State_Name: "Odisha",
    District_Name: "ANUGUL",
    Crop_Year: 1997,
    Season: "Whole Year",
    Crop: "Potato",
    Area: 524.0,
    Production: 4122.0,
  },
  {
    State_Name: "Puducherry",
    District_Name: "KARAIKAL",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Dry chillies",
    Area: 2.0,
    Production: 5.0,
  },
  {
    State_Name: "Puducherry",
    District_Name: "KARAIKAL",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Rice",
    Area: 909.0,
    Production: 2215.0,
  },
  {
    State_Name: "Puducherry",
    District_Name: "KARAIKAL",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Sesamum",
    Area: 44.0,
    Production: 20.0,
  },
  {
    State_Name: "Puducherry",
    District_Name: "KARAIKAL",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Sugarcane",
    Area: 84.0,
    Production: 6656.0,
  },
  {
    State_Name: "Puducherry",
    District_Name: "KARAIKAL",
    Crop_Year: 1998,
    Season: "Rabi",
    Crop: "Groundnut",
    Area: 52.0,
    Production: 55.0,
  },
  {
    State_Name: "Puducherry",
    District_Name: "KARAIKAL",
    Crop_Year: 1998,
    Season: "Rabi",
    Crop: "Rice",
    Area: 7550.0,
    Production: 14556.0,
  },
  {
    State_Name: "Puducherry",
    District_Name: "KARAIKAL",
    Crop_Year: 1998,
    Season: "Summer",
    Crop: "Cotton(lint)",
    Area: 288.0,
    Production: 220.0,
  },
  {
    State_Name: "Puducherry",
    District_Name: "KARAIKAL",
    Crop_Year: 1998,
    Season: "Summer",
    Crop: "Rice",
    Area: 153.0,
    Production: 383.0,
  },
  {
    State_Name: "Puducherry",
    District_Name: "KARAIKAL",
    Crop_Year: 1999,
    Season: "Kharif",
    Crop: "Bajra",
    Area: 170.0,
    Production: 470.0,
  },
  {
    State_Name: "Puducherry",
    District_Name: "KARAIKAL",
    Crop_Year: 1999,
    Season: "Kharif",
    Crop: "Cotton(lint)",
    Area: 168.0,
    Production: 876.0,
  },
  {
    State_Name: "Puducherry",
    District_Name: "KARAIKAL",
    Crop_Year: 1999,
    Season: "Kharif",
    Crop: "Dry ginger",
    Area: 34.0,
    Production: 21.0,
  },
  {
    State_Name: "Puducherry",
    District_Name: "KARAIKAL",
    Crop_Year: 1999,
    Season: "Kharif",
    Crop: "Groundnut",
    Area: 38.0,
    Production: 53.0,
  },
  {
    State_Name: "Puducherry",
    District_Name: "KARAIKAL",
    Crop_Year: 1999,
    Season: "Kharif",
    Crop: "Jowar",
    Area: 3.0,
    Production: 3.0,
  },
  {
    State_Name: "Puducherry",
    District_Name: "KARAIKAL",
    Crop_Year: 1999,
    Season: "Kharif",
    Crop: "Rice",
    Area: 8533.0,
    Production: 16642.0,
  },
  {
    State_Name: "Puducherry",
    District_Name: "KARAIKAL",
    Crop_Year: 1999,
    Season: "Rabi",
    Crop: "Moong(Green Gram)",
    Area: 71.0,
    Production: 44.0,
  },
  {
    State_Name: "Punjab",
    District_Name: "AMRITSAR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Arhar\\/Tur",
    Area: 1800.0,
    Production: 1400.0,
  },
  {
    State_Name: "Punjab",
    District_Name: "AMRITSAR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Bajra",
    Area: 1000.0,
    Production: 1000.0,
  },
  {
    State_Name: "Punjab",
    District_Name: "AMRITSAR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Maize",
    Area: 7000.0,
    Production: 14000.0,
  },
  {
    State_Name: "Punjab",
    District_Name: "AMRITSAR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Rice",
    Area: 292000.0,
    Production: 879000.0,
  },
  {
    State_Name: "Punjab",
    District_Name: "AMRITSAR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Sesamum",
    Area: 6000.0,
    Production: 1700.0,
  },
  {
    State_Name: "Punjab",
    District_Name: "AMRITSAR",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Urad",
    Area: 600.0,
    Production: 200.0,
  },
  {
    State_Name: "Punjab",
    District_Name: "AMRITSAR",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Gram",
    Area: 400.0,
    Production: 300.0,
  },
  {
    State_Name: "Punjab",
    District_Name: "AMRITSAR",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Masoor",
    Area: 700.0,
    Production: 400.0,
  },
  {
    State_Name: "Punjab",
    District_Name: "AMRITSAR",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Rapeseed &Mustard",
    Area: 8000.0,
    Production: 6000.0,
  },
  {
    State_Name: "Punjab",
    District_Name: "AMRITSAR",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Wheat",
    Area: 349000.0,
    Production: 1318000.0,
  },
  {
    State_Name: "Punjab",
    District_Name: "AMRITSAR",
    Crop_Year: 1997,
    Season: "Whole Year",
    Crop: "Cotton(lint)",
    Area: 5000.0,
    Production: 2000.0,
  },
  {
    State_Name: "Punjab",
    District_Name: "AMRITSAR",
    Crop_Year: 1997,
    Season: "Whole Year",
    Crop: "Moong(Green Gram)",
    Area: 8400.0,
    Production: 5300.0,
  },
  {
    State_Name: "Punjab",
    District_Name: "AMRITSAR",
    Crop_Year: 1997,
    Season: "Whole Year",
    Crop: "Sugarcane",
    Area: 11000.0,
    Production: 600000.0,
  },
  {
    State_Name: "Punjab",
    District_Name: "AMRITSAR",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Arhar\\/Tur",
    Area: 1100.0,
    Production: 700.0,
  },
  {
    State_Name: "Punjab",
    District_Name: "AMRITSAR",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Cotton(lint)",
    Area: 4000.0,
    Production: 3000.0,
  },
  {
    State_Name: "Rajasthan",
    District_Name: "AJMER",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Bajra",
    Area: 56600.0,
    Production: 30400.0,
  },
  {
    State_Name: "Rajasthan",
    District_Name: "AJMER",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Cotton(lint)",
    Area: 16000.0,
    Production: 31176.0,
  },
  {
    State_Name: "Rajasthan",
    District_Name: "AJMER",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Groundnut",
    Area: 7800.0,
    Production: 5100.0,
  },
  {
    State_Name: "Rajasthan",
    District_Name: "AJMER",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Jowar",
    Area: 105900.0,
    Production: 34600.0,
  },
  {
    State_Name: "Rajasthan",
    District_Name: "AJMER",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Maize",
    Area: 43600.0,
    Production: 33100.0,
  },
  {
    State_Name: "Rajasthan",
    District_Name: "AJMER",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Onion",
    Area: 2800.0,
    Production: 4500.0,
  },
  {
    State_Name: "Rajasthan",
    District_Name: "AJMER",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Rice",
    Area: 100.0,
    Production: 100.0,
  },
  {
    State_Name: "Rajasthan",
    District_Name: "AJMER",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Sesamum",
    Area: 8000.0,
    Production: 2000.0,
  },
  {
    State_Name: "Rajasthan",
    District_Name: "AJMER",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Sugarcane",
    Area: 100.0,
    Production: 6700.0,
  },
  {
    State_Name: "Rajasthan",
    District_Name: "AJMER",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Barley",
    Area: 24700.0,
    Production: 28900.0,
  },
  {
    State_Name: "Rajasthan",
    District_Name: "AJMER",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Gram",
    Area: 98800.0,
    Production: 94300.0,
  },
  {
    State_Name: "Rajasthan",
    District_Name: "AJMER",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Linseed",
    Area: 500.0,
    Production: 300.0,
  },
  {
    State_Name: "Rajasthan",
    District_Name: "AJMER",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Rapeseed &Mustard",
    Area: 36700.0,
    Production: 25400.0,
  },
  {
    State_Name: "Rajasthan",
    District_Name: "AJMER",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Wheat",
    Area: 79300.0,
    Production: 144500.0,
  },
  {
    State_Name: "Rajasthan",
    District_Name: "AJMER",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Arhar\\/Tur",
    Area: 3.0,
    Production: 4.0,
  },
  {
    State_Name: "Sikkim",
    District_Name: "EAST DISTRICT",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Maize",
    Area: 9690.0,
    Production: 16450.0,
  },
  {
    State_Name: "Sikkim",
    District_Name: "EAST DISTRICT",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Oilseeds total",
    Area: 20.0,
    Production: 10.0,
  },
  {
    State_Name: "Sikkim",
    District_Name: "EAST DISTRICT",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Rice",
    Area: 6690.0,
    Production: 9290.0,
  },
  {
    State_Name: "Sikkim",
    District_Name: "EAST DISTRICT",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Small millets",
    Area: 1600.0,
    Production: 1520.0,
  },
  {
    State_Name: "Sikkim",
    District_Name: "EAST DISTRICT",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Soyabean",
    Area: 1000.0,
    Production: 810.0,
  },
  {
    State_Name: "Sikkim",
    District_Name: "EAST DISTRICT",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Urad",
    Area: 980.0,
    Production: 740.0,
  },
  {
    State_Name: "Sikkim",
    District_Name: "EAST DISTRICT",
    Crop_Year: 1998,
    Season: "Rabi",
    Crop: "Barley",
    Area: 340.0,
    Production: 270.0,
  },
  {
    State_Name: "Sikkim",
    District_Name: "EAST DISTRICT",
    Crop_Year: 1998,
    Season: "Rabi",
    Crop: "Other  Rabi pulses",
    Area: 750.0,
    Production: 840.0,
  },
  {
    State_Name: "Sikkim",
    District_Name: "EAST DISTRICT",
    Crop_Year: 1998,
    Season: "Rabi",
    Crop: "Rapeseed &Mustard",
    Area: 2240.0,
    Production: 910.0,
  },
  {
    State_Name: "Sikkim",
    District_Name: "EAST DISTRICT",
    Crop_Year: 1998,
    Season: "Rabi",
    Crop: "Wheat",
    Area: 2720.0,
    Production: 2370.0,
  },
  {
    State_Name: "Sikkim",
    District_Name: "EAST DISTRICT",
    Crop_Year: 1998,
    Season: "Whole Year",
    Crop: "Pulses total",
    Area: 1730.0,
    Production: 1580.0,
  },
  {
    State_Name: "Sikkim",
    District_Name: "EAST DISTRICT",
    Crop_Year: 1998,
    Season: "Whole Year",
    Crop: "Total foodgrain",
    Area: 23370.0,
    Production: 28920.0,
  },
  {
    State_Name: "Sikkim",
    District_Name: "EAST DISTRICT",
    Crop_Year: 1999,
    Season: "Kharif",
    Crop: "Maize",
    Area: 9700.0,
    Production: 13473.0,
  },
  {
    State_Name: "Sikkim",
    District_Name: "EAST DISTRICT",
    Crop_Year: 1999,
    Season: "Kharif",
    Crop: "Rice",
    Area: 6720.0,
    Production: 9950.0,
  },
  {
    State_Name: "Sikkim",
    District_Name: "EAST DISTRICT",
    Crop_Year: 1999,
    Season: "Kharif",
    Crop: "Soyabean",
    Area: 1000.0,
    Production: 830.0,
  },
  {
    State_Name: "Tamil Nadu",
    District_Name: "ARIYALUR",
    Crop_Year: 2008,
    Season: "Kharif",
    Crop: "Rice",
    Area: 24574.0,
    Production: null,
  },
  {
    State_Name: "Tamil Nadu",
    District_Name: "ARIYALUR",
    Crop_Year: 2008,
    Season: "Whole Year",
    Crop: "Arhar\\/Tur",
    Area: 209.0,
    Production: null,
  },
  {
    State_Name: "Tamil Nadu",
    District_Name: "ARIYALUR",
    Crop_Year: 2008,
    Season: "Whole Year",
    Crop: "Bajra",
    Area: 565.0,
    Production: null,
  },
  {
    State_Name: "Tamil Nadu",
    District_Name: "ARIYALUR",
    Crop_Year: 2008,
    Season: "Whole Year",
    Crop: "Banana",
    Area: 190.0,
    Production: null,
  },
  {
    State_Name: "Tamil Nadu",
    District_Name: "ARIYALUR",
    Crop_Year: 2008,
    Season: "Whole Year",
    Crop: "Cashewnut",
    Area: 31113.0,
    Production: null,
  },
  {
    State_Name: "Tamil Nadu",
    District_Name: "ARIYALUR",
    Crop_Year: 2008,
    Season: "Whole Year",
    Crop: "Castor seed",
    Area: 27.0,
    Production: null,
  },
  {
    State_Name: "Tamil Nadu",
    District_Name: "ARIYALUR",
    Crop_Year: 2008,
    Season: "Whole Year",
    Crop: "Coconut",
    Area: 335.0,
    Production: null,
  },
  {
    State_Name: "Tamil Nadu",
    District_Name: "ARIYALUR",
    Crop_Year: 2008,
    Season: "Whole Year",
    Crop: "Coriander",
    Area: 460.0,
    Production: null,
  },
  {
    State_Name: "Tamil Nadu",
    District_Name: "ARIYALUR",
    Crop_Year: 2008,
    Season: "Whole Year",
    Crop: "Cotton(lint)",
    Area: 3566.0,
    Production: null,
  },
  {
    State_Name: "Tamil Nadu",
    District_Name: "ARIYALUR",
    Crop_Year: 2008,
    Season: "Whole Year",
    Crop: "Dry chillies",
    Area: 1774.0,
    Production: null,
  },
  {
    State_Name: "Tamil Nadu",
    District_Name: "ARIYALUR",
    Crop_Year: 2008,
    Season: "Whole Year",
    Crop: "Groundnut",
    Area: 14528.0,
    Production: null,
  },
  {
    State_Name: "Tamil Nadu",
    District_Name: "ARIYALUR",
    Crop_Year: 2008,
    Season: "Whole Year",
    Crop: "Jowar",
    Area: 6674.0,
    Production: null,
  },
  {
    State_Name: "Tamil Nadu",
    District_Name: "ARIYALUR",
    Crop_Year: 2008,
    Season: "Whole Year",
    Crop: "Maize",
    Area: 9797.0,
    Production: null,
  },
  {
    State_Name: "Tamil Nadu",
    District_Name: "ARIYALUR",
    Crop_Year: 2008,
    Season: "Whole Year",
    Crop: "Moong(Green Gram)",
    Area: 39.0,
    Production: null,
  },
  {
    State_Name: "Tamil Nadu",
    District_Name: "ARIYALUR",
    Crop_Year: 2008,
    Season: "Whole Year",
    Crop: "Onion",
    Area: 21.0,
    Production: null,
  },
  {
    State_Name: "Telangana",
    District_Name: "ADILABAD",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Arhar\\/Tur",
    Area: 32200.0,
    Production: 1100.0,
  },
  {
    State_Name: "Telangana",
    District_Name: "ADILABAD",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Castor seed",
    Area: 2600.0,
    Production: 700.0,
  },
  {
    State_Name: "Telangana",
    District_Name: "ADILABAD",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Cotton(lint)",
    Area: 144900.0,
    Production: 66500.0,
  },
  {
    State_Name: "Telangana",
    District_Name: "ADILABAD",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Dry chillies",
    Area: 5500.0,
    Production: 3100.0,
  },
  {
    State_Name: "Telangana",
    District_Name: "ADILABAD",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Jowar",
    Area: 58200.0,
    Production: 31500.0,
  },
  {
    State_Name: "Telangana",
    District_Name: "ADILABAD",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Maize",
    Area: 23900.0,
    Production: 63000.0,
  },
  {
    State_Name: "Telangana",
    District_Name: "ADILABAD",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Moong(Green Gram)",
    Area: 20600.0,
    Production: 3600.0,
  },
  {
    State_Name: "Telangana",
    District_Name: "ADILABAD",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Other Kharif pulses",
    Area: 1500.0,
    Production: 200.0,
  },
  {
    State_Name: "Telangana",
    District_Name: "ADILABAD",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Rice",
    Area: 30600.0,
    Production: 29100.0,
  },
  {
    State_Name: "Telangana",
    District_Name: "ADILABAD",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Sesamum",
    Area: 21700.0,
    Production: 1000.0,
  },
  {
    State_Name: "Telangana",
    District_Name: "ADILABAD",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Sugarcane",
    Area: 200.0,
    Production: 15400.0,
  },
  {
    State_Name: "Telangana",
    District_Name: "ADILABAD",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Sunflower",
    Area: 5200.0,
    Production: 2300.0,
  },
  {
    State_Name: "Telangana",
    District_Name: "ADILABAD",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Urad",
    Area: 19500.0,
    Production: 6600.0,
  },
  {
    State_Name: "Telangana",
    District_Name: "ADILABAD",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Dry chillies",
    Area: 700.0,
    Production: 1600.0,
  },
  {
    State_Name: "Telangana",
    District_Name: "ADILABAD",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Gram",
    Area: 4000.0,
    Production: 500.0,
  },
  {
    State_Name: "Tripura",
    District_Name: "DHALAI",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Arhar\\/Tur",
    Area: 135.0,
    Production: 100.0,
  },
  {
    State_Name: "Tripura",
    District_Name: "DHALAI",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Cotton(lint)",
    Area: 461.0,
    Production: 511.0,
  },
  {
    State_Name: "Tripura",
    District_Name: "DHALAI",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Groundnut",
    Area: 535.0,
    Production: 530.0,
  },
  {
    State_Name: "Tripura",
    District_Name: "DHALAI",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Jute",
    Area: 125.0,
    Production: 1000.0,
  },
  {
    State_Name: "Tripura",
    District_Name: "DHALAI",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Maize",
    Area: 615.0,
    Production: 460.0,
  },
  {
    State_Name: "Tripura",
    District_Name: "DHALAI",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Mesta",
    Area: 460.0,
    Production: 3374.0,
  },
  {
    State_Name: "Tripura",
    District_Name: "DHALAI",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Moong(Green Gram)",
    Area: 120.0,
    Production: 60.0,
  },
  {
    State_Name: "Tripura",
    District_Name: "DHALAI",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Other Kharif pulses",
    Area: 323.0,
    Production: 225.0,
  },
  {
    State_Name: "Tripura",
    District_Name: "DHALAI",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Rice",
    Area: 34010.0,
    Production: 56605.0,
  },
  {
    State_Name: "Tripura",
    District_Name: "DHALAI",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Sesamum",
    Area: 185.0,
    Production: 85.0,
  },
  {
    State_Name: "Tripura",
    District_Name: "DHALAI",
    Crop_Year: 1998,
    Season: "Kharif",
    Crop: "Urad",
    Area: 170.0,
    Production: 81.0,
  },
  {
    State_Name: "Tripura",
    District_Name: "DHALAI",
    Crop_Year: 1998,
    Season: "Rabi",
    Crop: "Gram",
    Area: 29.0,
    Production: 20.0,
  },
  {
    State_Name: "Tripura",
    District_Name: "DHALAI",
    Crop_Year: 1998,
    Season: "Rabi",
    Crop: "Groundnut",
    Area: 170.0,
    Production: 159.0,
  },
  {
    State_Name: "Tripura",
    District_Name: "DHALAI",
    Crop_Year: 1998,
    Season: "Rabi",
    Crop: "Masoor",
    Area: 40.0,
    Production: 16.0,
  },
  {
    State_Name: "Tripura",
    District_Name: "DHALAI",
    Crop_Year: 1998,
    Season: "Rabi",
    Crop: "Moong(Green Gram)",
    Area: 107.0,
    Production: 44.0,
  },
  {
    State_Name: "Uttar Pradesh",
    District_Name: "AGRA",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Arhar\\/Tur",
    Area: 6538.0,
    Production: 9664.0,
  },
  {
    State_Name: "Uttar Pradesh",
    District_Name: "AGRA",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Bajra",
    Area: 99898.0,
    Production: 147994.0,
  },
  {
    State_Name: "Uttar Pradesh",
    District_Name: "AGRA",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Groundnut",
    Area: 27.0,
    Production: 22.0,
  },
  {
    State_Name: "Uttar Pradesh",
    District_Name: "AGRA",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Jowar",
    Area: 725.0,
    Production: 406.0,
  },
  {
    State_Name: "Uttar Pradesh",
    District_Name: "AGRA",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Maize",
    Area: 138.0,
    Production: 316.0,
  },
  {
    State_Name: "Uttar Pradesh",
    District_Name: "AGRA",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Moong(Green Gram)",
    Area: 97.0,
    Production: 28.0,
  },
  {
    State_Name: "Uttar Pradesh",
    District_Name: "AGRA",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Moth",
    Area: 15.0,
    Production: 8.0,
  },
  {
    State_Name: "Uttar Pradesh",
    District_Name: "AGRA",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Oilseeds total",
    Area: 98911.0,
    Production: 58881.0,
  },
  {
    State_Name: "Uttar Pradesh",
    District_Name: "AGRA",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Onion",
    Area: 110.0,
    Production: 1088.0,
  },
  {
    State_Name: "Uttar Pradesh",
    District_Name: "AGRA",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Rice",
    Area: 935.0,
    Production: 2073.0,
  },
  {
    State_Name: "Uttar Pradesh",
    District_Name: "AGRA",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Sesamum",
    Area: 1784.0,
    Production: 416.0,
  },
  {
    State_Name: "Uttar Pradesh",
    District_Name: "AGRA",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Soyabean",
    Area: 4.0,
    Production: 4.0,
  },
  {
    State_Name: "Uttar Pradesh",
    District_Name: "AGRA",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Total foodgrain",
    Area: 258075.0,
    Production: 602076.0,
  },
  {
    State_Name: "Uttar Pradesh",
    District_Name: "AGRA",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Urad",
    Area: 651.0,
    Production: 345.0,
  },
  {
    State_Name: "Uttar Pradesh",
    District_Name: "AGRA",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Barley",
    Area: 10865.0,
    Production: 35423.0,
  },
  {
    State_Name: "Uttarakhand",
    District_Name: "ALMORA",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Arhar\\/Tur",
    Area: 5.0,
    Production: 2.0,
  },
  {
    State_Name: "Uttarakhand",
    District_Name: "ALMORA",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Horse-gram",
    Area: 1244.0,
    Production: 684.0,
  },
  {
    State_Name: "Uttarakhand",
    District_Name: "ALMORA",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Maize",
    Area: 1922.0,
    Production: 2504.0,
  },
  {
    State_Name: "Uttarakhand",
    District_Name: "ALMORA",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Other Cereals & Millets",
    Area: 107.0,
    Production: 32.0,
  },
  {
    State_Name: "Uttarakhand",
    District_Name: "ALMORA",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Other Kharif pulses",
    Area: 1539.0,
    Production: 980.0,
  },
  {
    State_Name: "Uttarakhand",
    District_Name: "ALMORA",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Potato",
    Area: 419.0,
    Production: 9302.0,
  },
  {
    State_Name: "Uttarakhand",
    District_Name: "ALMORA",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Ragi",
    Area: 31583.0,
    Production: 34356.0,
  },
  {
    State_Name: "Uttarakhand",
    District_Name: "ALMORA",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Rice",
    Area: 21297.0,
    Production: 21003.0,
  },
  {
    State_Name: "Uttarakhand",
    District_Name: "ALMORA",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Sesamum",
    Area: 123.0,
    Production: 19.0,
  },
  {
    State_Name: "Uttarakhand",
    District_Name: "ALMORA",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Small millets",
    Area: 15012.0,
    Production: 16709.0,
  },
  {
    State_Name: "Uttarakhand",
    District_Name: "ALMORA",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Soyabean",
    Area: 273.0,
    Production: 150.0,
  },
  {
    State_Name: "Uttarakhand",
    District_Name: "ALMORA",
    Crop_Year: 2000,
    Season: "Kharif",
    Crop: "Urad",
    Area: 882.0,
    Production: 368.0,
  },
  {
    State_Name: "Uttarakhand",
    District_Name: "ALMORA",
    Crop_Year: 2000,
    Season: "Rabi",
    Crop: "Barley",
    Area: 3436.0,
    Production: 2934.0,
  },
  {
    State_Name: "Uttarakhand",
    District_Name: "ALMORA",
    Crop_Year: 2000,
    Season: "Rabi",
    Crop: "Masoor",
    Area: 1083.0,
    Production: 552.0,
  },
  {
    State_Name: "Uttarakhand",
    District_Name: "ALMORA",
    Crop_Year: 2000,
    Season: "Rabi",
    Crop: "other oilseeds",
    Area: 5.0,
    Production: 2.0,
  },
  {
    State_Name: "West Bengal",
    District_Name: "24 PARAGANAS NORTH",
    Crop_Year: 1997,
    Season: "Autumn",
    Crop: "Rice",
    Area: 15017.0,
    Production: 33840.0,
  },
  {
    State_Name: "West Bengal",
    District_Name: "24 PARAGANAS NORTH",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Jute",
    Area: 52568.0,
    Production: 677510.0,
  },
  {
    State_Name: "West Bengal",
    District_Name: "24 PARAGANAS NORTH",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Mesta",
    Area: 690.0,
    Production: 6710.0,
  },
  {
    State_Name: "West Bengal",
    District_Name: "24 PARAGANAS NORTH",
    Crop_Year: 1997,
    Season: "Kharif",
    Crop: "Urad",
    Area: 1992.0,
    Production: 1310.0,
  },
  {
    State_Name: "West Bengal",
    District_Name: "24 PARAGANAS NORTH",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Gram",
    Area: 267.0,
    Production: 160.0,
  },
  {
    State_Name: "West Bengal",
    District_Name: "24 PARAGANAS NORTH",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Khesari",
    Area: 117.0,
    Production: 90.0,
  },
  {
    State_Name: "West Bengal",
    District_Name: "24 PARAGANAS NORTH",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Masoor",
    Area: 6179.0,
    Production: 3720.0,
  },
  {
    State_Name: "West Bengal",
    District_Name: "24 PARAGANAS NORTH",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Moong(Green Gram)",
    Area: 65.0,
    Production: 49.0,
  },
  {
    State_Name: "West Bengal",
    District_Name: "24 PARAGANAS NORTH",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Oilseeds total",
    Area: 4205800.0,
    Production: 3183800.0,
  },
  {
    State_Name: "West Bengal",
    District_Name: "24 PARAGANAS NORTH",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Urad",
    Area: 295.0,
    Production: 58.0,
  },
  {
    State_Name: "West Bengal",
    District_Name: "24 PARAGANAS NORTH",
    Crop_Year: 1997,
    Season: "Rabi",
    Crop: "Wheat",
    Area: 6790.0,
    Production: 11950.0,
  },
  {
    State_Name: "West Bengal",
    District_Name: "24 PARAGANAS NORTH",
    Crop_Year: 1997,
    Season: "Summer",
    Crop: "Moong(Green Gram)",
    Area: 175.0,
    Production: 5.0,
  },
  {
    State_Name: "West Bengal",
    District_Name: "24 PARAGANAS NORTH",
    Crop_Year: 1997,
    Season: "Summer",
    Crop: "Rice",
    Area: 98044.0,
    Production: 269690.0,
  },
  {
    State_Name: "West Bengal",
    District_Name: "24 PARAGANAS NORTH",
    Crop_Year: 1997,
    Season: "Whole Year",
    Crop: "Arecanut",
    Area: 1345.0,
    Production: 1274.0,
  },
  {
    State_Name: "West Bengal",
    District_Name: "24 PARAGANAS NORTH",
    Crop_Year: 1997,
    Season: "Whole Year",
    Crop: "Arhar\\/Tur",
    Area: 45.0,
    Production: 40.0,
  },
];

export default statedata;